# Generated by Django 5.2.17 on 2026-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspoint',
            name='encashment_condition',
            field=models.CharField(blank=True, choices=[('==', 'equals'), ('>', 'greater than'), ('<', 'less than'), ('>=', 'greater than or equal'), ('<=', 'less than or equal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbonuspoint',
            name='encashment_condition',
            field=models.CharField(blank=True, choices=[('==', 'equals'), ('>', 'greater than'), ('<', 'less than'), ('>=', 'greater than or equal'), ('<=', 'less than or equal')], max_length=100, null=True),
        ),
    ]
