# Generated by Django 5.2.17 on 2026-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_seed_default_export_permission"),
        ("employee", "0006_alter_bonuspoint_encashment_condition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="specific_employees",
        ),
        migrations.AddField(
            model_name="policy",
            name="department",
            field=models.ManyToManyField(blank=True, to="base.department"),
        ),
        migrations.AddField(
            model_name="policy",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used only when 'Publish' is disabled below -- restricts the policy to these employees plus anyone in the selected department(s) or job position(s).",
                related_name="policy_employees",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="filtered_employees",
            field=models.ManyToManyField(
                editable=False,
                related_name="policy_filtered_employees",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="job_position",
            field=models.ManyToManyField(
                blank=True, to="base.jobposition", verbose_name="Job Position"
            ),
        ),
        migrations.AlterField(
            model_name="policy",
            name="is_visible_to_all",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the policy is visible to every employee in the selected company. Disable it to restrict visibility to the employees/department/job position selected above.",
                verbose_name="Publish to all",
            ),
        ),
    ]
