# Generated by Django 5.2.17 on 2026-09-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("asset", "0007_assetgeneralsetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_tracking_id",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Serial No."
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="expiry_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Warranty Expiry Date"
            ),
        ),
        migrations.AlterField(
            model_name="assetitem",
            name="tracking_id",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Serial No."
            ),
        ),
    ]
