# Generated by Django 5.2.17 on 2026-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_alter_bonuspoint_encashment_condition_and_more"),
        (
            "report",
            "0002_reporttemplate_is_standard_reporttemplate_visibility_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportsubscription",
            name="recipients",
        ),
        migrations.AddField(
            model_name="reportsubscription",
            name="recipients_employees",
            field=models.ManyToManyField(
                blank=True,
                related_name="report_subscriptions",
                to="employee.employee",
                verbose_name="Recipients",
            ),
        ),
    ]
