# Generated by Django 5.2.17 on 2026-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_seed_default_export_permission"),
        (
            "employee",
            "0007_remove_policy_specific_employees_policy_department_and_more",
        ),
        ("payroll", "0008_payslip_payslip_end_date_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="department",
            field=models.ManyToManyField(blank=True, to="base.department"),
        ),
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used only when 'Apply to all employees' is disabled -- restricts Leave Encashment to these employees plus anyone in the selected department(s) or job position(s).",
                related_name="encashment_settings_employees",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="filtered_employees",
            field=models.ManyToManyField(
                editable=False,
                related_name="encashment_settings_filtered_employees",
                to="employee.employee",
            ),
        ),
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="is_applicable_to_all",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, every employee can use Leave Encashment. Disable it to restrict it to the employees/department/job position selected below.",
                verbose_name="Apply to all employees",
            ),
        ),
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="job_position",
            field=models.ManyToManyField(
                blank=True, to="base.jobposition", verbose_name="Job Position"
            ),
        ),
        migrations.AddField(
            model_name="encashmentgeneralsettings",
            name="leave_encashment_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When disabled, employees won't see the Leave Encashments section under Reimbursements & Encashments.",
                verbose_name="Enable Leave Encashment",
            ),
        ),
    ]
