# Generated by Django 5.2.17 on 2026-09-15 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="verb_ar",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="verb_de",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="verb_en",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="verb_es",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="verb_fr",
        ),
    ]
